name: Require Members Approval

on:
  push:
    branches: [master, main]
  

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: send approval
        uses: TigerWest/slack-approval@v1.0.1
        env:
          SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        timeout-minutes: 10
        with:
            approvers: U07TW3805ST,U07U7PSMCFP
            minimumApprovalCount: 2
            baseMessagePayload: |
              {
                "text": "base messaage approve reuqest"
              }
            successMessagePayload: |
              {
                "text": "success messaage approve reuqest"
              }
            failMessagePayload: |
              {
                "text": "fail messaage approve reuqest"
              }
