name: multiple environments

on:
  push:
    tags:
      - "V[0-9]+.[0-9]+.[0-9]+"
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

env:
  TAG_NAME: ${{ github.ref_name }}

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Development
        run: echo "Deploying to Development Environment"

  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        run: echo "Deploying to Production Environment"
