name: Build test

on:
  workflow_dispatch:

jobs:
  
    approval:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - uses: actions/create-github-app-token@v1
              id: app-token
              with:
                # required
                app-id: ${{ secrets.APP_ID }}
                private-key: ${{ secrets.PRIVATE_KEY }}
                repositories: |
                   deployment-protection
                   flux-upgrade
            - name: Checkout
              uses: actions/checkout@v4
              with:
                token: ${{ steps.app-token.outputs.token }}
                repository: 'creeram/flux-upgrade'
                ref: '0.0.1'
                path: ./flux-upgrade
                persist-credentials: false
            - name: List files in repository root
              run: ls -al

      # To list files in a specific directory, specify the path
            - name: List files in a specific directory
              run: ls -al ./slack-workflow-approval
